mod bda_compute;
mod bda_immediate;
mod resolution_uniform;
mod target_distr;

pub use bda_compute::{
    BDAComputeDiff, ComputeTask as BdaComputeTask, PipelineStateHolder as BdaComputeState,
};
pub use bda_immediate::{
    BDADiff, PipelineStateHolder as BDADiffState, shader_bindings::RWMHAcceptRecord,
};
pub use resolution_uniform::INITIAL_RENDER_SIZE;
pub use target_distr::{NormalDistribution, PipelineStateHolder as MMGState, TargetDistribution};

#[macro_export]
macro_rules! create_shader_module {
    ($shader_name:expr, mod $module_name: ident) => {
        #[expect(
            unused,
            elided_lifetimes_in_paths,
            reason = "autogenerated"
        )]
        pub mod $module_name {
            include!(concat!(
                env!("OUT_DIR"),
                "/shaders_bindings/",
                $shader_name,
                ".rs"
            ));
            pub use bind_groups::*;
        }
    };
    ($shader_name:expr, mod $module_name: ident; no redefine) => {
        #[expect(
            unused,
            clippy::module_name_repetitions,
            reason = "Autogenerated"
        )]
        pub mod $module_name {
            include!(concat!(
                env!("OUT_DIR"),
                "/shaders_bindings/",
                $shader_name,
                ".rs"
            ));
        }
    };
    ($shader_name:expr) => {
        create_shader_module!($shader_name, mod shader_bindings);
    };
}

create_shader_module!("fullscreen_quad.vertex", mod fullscreen_quad; no redefine);
