[package]
name = "mcmc-demo"
version = "0.1.0"
authors = ["Samuel Maier <9smtm6@gmail.com>"]
edition = "2021"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[features]
default = [
    "all_rngs",
    "profile",
    "shipped_fonts",
    "tracing",
    "x11",
    "persistence",
]
persistence = [
    "eframe/persistence",
    "nalgebra/serde-serialize",
    "rand/serde1",
    "rand_chacha/serde1",
    "rand_distr/serde1",
    "rand_pcg/serde1",
    "rand_xorshift/serde1",
    "rand_xoshiro/serde1",
    # not needed currently.
    # "wgpu/serde",
    "dep:serde",
]
# doesnt work, since it can't translate storagebuffers.
# And my experiments with passing stuff via textures was not successful.
# webgl_compat = ["wgpu/webgl"]
x11 = ["eframe/x11"]
shipped_fonts = ["eframe/default_fonts"]
profile = ["dep:puffin", "dep:puffin_http", "eframe/puffin"]
tracing = [
    "dep:tracing",
    "dep:tracing-log",
    "dep:tracing-subscriber",
    # TODO: ought to be also included only based on target, but I cant seem to find a way to do that.
    "dep:tracing-web",
    "dep:time",
    # "temporarily removed". Reinstatement issue: https://github.com/gfx-rs/wgpu/issues/5974
    # "wgpu/trace",
    "rand/log",
]
all_rngs = [
    "rng_pcg",
    # "rng_small",
    "rng_xorshift",
    "rng_xoshiro",
    "rng_chacha",
]
rng_pcg = ["dep:rand_pcg"]
rng_chacha = ["dep:rand_chacha"]
rng_xoshiro = ["dep:rand_xoshiro"]
rng_xorshift = ["dep:rand_xorshift"]
# rng_small = ["rand/small_rng"]

[dependencies]
bytemuck = { version = "1.16.0" }
delegate = "0.12.0"
eframe = { version = "0.28.1", default-features = false, features = [
    "wgpu",
    "wayland",
] }
egui = "0.28.1"
enum_dispatch = "0.3.13"
getrandom = { version = "0.2.15", features = ["js"] }
log = "0.4"
nalgebra = { version = "0.33.0" }
puffin = { version = "0.19.0", optional = true }
puffin_http = { version = "0.16.0", optional = true }
rand = { version = "0.8.5", default-features = false, features = [
    "log",
    "std",
] }
rand_chacha = { version = "0.3.1", optional = true }
rand_distr = "0.4.3"
rand_pcg = {version = "0.3.1", optional = true}
rand_xorshift = { version = "0.3.0", optional = true }
rand_xoshiro = { version = "0.6.0", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
strum = { version = "0.26.3", features = ["derive"] }
time = { version = "0.3.36", features = ["wasm-bindgen"], optional = true }
tracing = { version = "0.1.40", optional = true }
tracing-log = { version = "0.2.0", optional = true }
tracing-subscriber = { version = "0.3.18", optional = true, features = [
    "env-filter",
    "fmt",
    "time",
] }
wasm_thread = "0.3.0"
wgpu = { version = "22.1", features = ["webgpu"] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.5"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-web = { version = "0.1.3", optional = true }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.69", features = ["Navigator", "Gpu"] }
wasm-bindgen = "=0.2.92"
console_error_panic_hook = "0.1.7"

[build-dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
regex = "1.10.6"
wgsl_bindgen = "0.15"
wgsl_to_wgpu = "0.9.0"

[profile.release]
opt-level = 2 # fast and small wasm
# opt-level = "z" #note the override of packages
# see: https://fasterthanli.me/articles/why-is-my-rust-build-so-slow#link-time-optimization-lto
# lto = "thin"
# codegen-units = 1
# panic = "abort"
# strip = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
# the release on patched branches MUST match the set version above,# otherwise cargo will ignore this (it will warn about it though).

# If you want to use the bleeding edge version of egui and eframe:
# egui = { git = "https://github.com/emilk/egui", branch = "master" }
# eframe = { git = "https://github.com/emilk/egui", branch = "master" }

eframe = { git = "https://github.com/9smtm6/egui", branch = "patched" }
egui = { git = "https://github.com/9smtm6/egui", branch = "patched" }

wgsl_to_wgpu = { git = "https://github.com/9SMTM6/wgsl_to_wgpu", branch = "clean_patched" }
# wgsl_to_wgpu = { path = "../wgsl_to_wgpu/wgsl_to_wgpu" }
# wgpu = { git = "https://github.com/9smtm6/wgpu", branch = "patched" }

# If you fork https://github.com/emilk/egui you can test with:
# egui = { path = "../egui/crates/egui" }
# eframe = { path = "../egui/crates/eframe" }

[lints.rust]
unsafe-op-in-unsafe-fn = "warn"
let_underscore_drop = "deny"
rust_2024_compatibility = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
# unstable
# must_not_suspend = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
# this isnt actually a thing outside of nightly
allow_attributes_without_reason = "allow"
branches_sharing_code = "warn"
checked_conversions = "warn"
cognitive_complexity = "warn"
dbg_macro = "warn"
# "warn_on_ci"
expl_impl_clone_on_copy = "deny"
float_cmp = "warn"
fn_params_excessive_bools = "warn"
indexing_slicing = "warn"
manual_ok_or = "warn"
missing_const_for_fn = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
module_name_repetitions = "warn"
# causes a bunch (!) of warnings, but all from dependencies.
# could be solved by either making PRs to dependencies to unify,
# or by [ignoring](https://rust-lang.github.io/rust-clippy/master/index.html#/multiple_crate_versions):
# set `allowed-duplicate-crates`
#
# multiple_crate_versions = "warn"
needless_borrowed_reference = "allow"
needless_pass_by_value = "warn"
no_effect_underscore_binding = "warn"
pattern_type_mismatch = "warn"
rc_buffer = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
separated_literal_suffix = "warn"
shadow_unrelated = "warn"
struct_excessive_bools = "warn"
# todo = "warn"
# "warn_on_ci"
undocumented_unsafe_blocks = "warn"
unnested_or_patterns = "warn"
unreadable_literal = "warn"
# unwrap_used = "warn"
# "warn_on_ci"
used_underscore_binding = "warn"
