[build]
# minify="on_release"

# these might at one point help with compression.
# currently with serve I had to manually run `brotli dist/mcmc_demo*bg.wasm` after `trunk serve --release`,
# and that trunk had to be modified to use these precompressed assets, as described here:
# https://github.com/trunk-rs/trunk/issues/91#issuecomment-2184210744
# filehash = false
# [[hooks]]
# stage = "post_build"
# command = "brotli"
# command_arguments = ["dist/mcmc_demo_bg.wasm"]
