generate_favicon:
    typst compile assets/favicon.typ assets/favicon.intermediate.svg
    svgcleaner assets/favicon.intermediate.svg assets/favicon.svg
    rsvg-convert --width 256 --height 256 assets/favicon.svg > assets/favicon-256.png

# Generate new matching `index.fat.html` from `index.html` and `index.fat.html.patch`
patch_fat_html:
    patch index.html -o index.fat.html < index.fat.html.patch

# Generate new patch file from matched `index.html` and `index.fat.html`
diff_fat_html:
    diff -u index.html index.fat.html > index.fat.html.patch || true

benchmark_wasm_size compression_level='4':
    # ignore files in my global ~/.cargo/config.toml
    # wont work on other setups!
    export RUSTFLAGS=
    export CARGO_BUILD_INCREMENTAL=false
    just trunk_fat build --release
    just trunk_slim build --release
    brotli -q {{compression_level}} -f dist/*/mcmc-demo*_bg.wasm
    lsd -lah dist/*/mcmc-demo*_bg.was*

trunk_fat +cmd="serve": patch_fat_html
    trunk {{cmd}} --config Trunk.fat.toml

trunk_slim +cmd="serve":
    trunk {{cmd}}

trunk_deploy cmd="serve" +flags="":
    just dist/trunk_deploy {{cmd}} {{flags}}

diff_deploy_html:
    just dist/diff_deploy_html
