generate_favicon:
    typst compile assets/favicon.typ assets/favicon.intermediate.svg
    svgcleaner assets/favicon.intermediate.svg assets/favicon.svg

# Generate new matching `index.fat.html` from `index.html` and `index.fat.html.patch`
patch_fat_html:
    patch index.html -o index.fat.html < index.fat.html.patch

# Generate new patch file from matched `index.html` and `index.fat.html`
diff_fat_html:
    diff -u index.html index.fat.html > index.fat.html.patch || 0

benchmark_wasm_size compression_level='4':
    # ignore files in my global ~/.cargo/config.toml
    # wont work on other setups!
    export RUSTFLAGS=
    export CARGO_BUILD_INCREMENTAL=false
    trunk build --release
    trunk build --config Trunk.fat.toml --release
    brotli -q {{compression_level}} -f dist/*/mcmc-demo*_bg.wasm
    lsd -lah dist/*/mcmc-demo*_bg.was*

trunk_fat: patch_fat_html
    trunk serve --config Trunk.fat.toml

trunk_slim:
    trunk serve
