[build]
minify = "on_release"
dist = "dist/slim"
# don't update dependencies
locked = true

[serve.headers]
# see ./assets/_headers for more documentation
"cross-origin-embedder-policy"= "require-corp"
"cross-origin-opener-policy"= "same-origin"
"cross-origin-resource-policy"= "same-site"

# hotfix for CI failure (probably caused due to newer wasm-bindgen which is selected based on Cargo.toml version)
[tools]
wasm_opt = "version_118"
