name: Build Webpage

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on: [push, pull_request]

env:
  RUST_TOOLCHAIN_VERSION: "nightly-2024-08-02"

# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to artifacts/* branch.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: fat
            config_file: Trunk.fat.toml
          - name: slim
            config_file: Trunk.toml
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{env.RUST_TOOLCHAIN_VERSION}}
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      - name: Build ${{ matrix.name }}
        # using --public-url something will allow trunk to modify all the href paths like from favicon.ico to repo_name/favicon.ico .
        # this is necessary for github pages where the site is deployed to username.github.io/repo_name and all files must be requested
        # relatively as eframe_template/favicon.ico. if we skip public-url option, the href paths will instead request username.github.io/favicon.ico which
        # will obviously return error 404 not found.
        run: ./trunk build --config ${{ matrix.config_file }} --release --public-url __RENAME_ME__
      - name: Precompress
        run: brotli ./dist/*/mcmc-demo*bg.wasm
      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-artifacts
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          # I just need a git repo with correct remote for the deploy action
          sparse-checkout: .
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*-artifacts"
          path: dist
          merge-multiple: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: artifacts/webpage/${{ github.head_ref || github.ref_name }}
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true
